@role('super-admin')
    @include('livewire.pages.dashboard.super-admin')
@endrole
@role('admin-ju')
    @include('livewire.pages.dashboard.admin-ju')
@endrole
@role('penyemak')
    @include('livewire.pages.dashboard.penyemak')
@endrole
@role('pelulus')
    @include('livewire.pages.dashboard.admin-ju')
@endrole
@role('doctor')
    @include('livewire.pages.dashboard.admin-ju')
@endrole
@role('klinik-hq')
    @include('livewire.pages.dashboard.admin-ju')
@endrole
@role('pembantu-klinik')
    @include('livewire.pages.dashboard.admin-ju')
@endrole
@role('agensi')
    @include('livewire.pages.dashboard.agensi')
@endrole